# Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

1. LIST 

In [36]:
import numpy as np
import pandas as pd

In [37]:
# List
list_1 = [90, 10, 20, 30, 40, 50]
print("List:", list_1)

List: [90, 10, 20, 30, 40, 50]


In [38]:
# append
list_1.append(60)
print("Append:", list_1)

# extend
list_1.extend([70, 80])
print("Extend:", list_1)

# insert
list_1.insert(1, 15)
print("Insert:", list_1)

# remove
list_1.remove(15)
print("Remove:", list_1)

# pop
list_1.pop()
print("Pop:", list_1)

# index
print("Index of 40:", list_1.index(40))

# count
print("Count of 20:", list_1.count(20))

# sort
list_1.sort()
print("Sort:", list_1)

# reverse
list_1.reverse()
print("Reverse:", list_1)

# clear
list_1.clear()
print("Clear:", list_1)

Append: [90, 10, 20, 30, 40, 50, 60]
Extend: [90, 10, 20, 30, 40, 50, 60, 70, 80]
Insert: [90, 15, 10, 20, 30, 40, 50, 60, 70, 80]
Remove: [90, 10, 20, 30, 40, 50, 60, 70, 80]
Pop: [90, 10, 20, 30, 40, 50, 60, 70]
Index of 40: 4
Count of 20: 1
Sort: [10, 20, 30, 40, 50, 60, 70, 90]
Reverse: [90, 70, 60, 50, 40, 30, 20, 10]
Clear: []


2. TUPLE

In [39]:
students = ("Shrutee", "Yash", "Jiya")

# Tuples are immutable (cannot be changed after creation).
# Trying to modify gives: TypeError
# If we try to change second value
# eg. students[1] = "Rahul"   # This will give an error

3. SET

In [40]:
set1 = {1, 2, 3, 3, 4, 5, 5}
print("Set:", set1)

# Sets remove duplicates automatically.

Set: {1, 2, 3, 4, 5}


4. DICTIONARY 

In [41]:
person = {
    "name": "Shrutee",
    "age": 22,
    "city": "Mumbai"
}
print("Updated Dictionary:", person)

Updated Dictionary: {'name': 'Shrutee', 'age': 22, 'city': 'Mumbai'}


In [42]:
# Update age
person["age"] = 23
print("Updated Dictionary:", person)

Updated Dictionary: {'name': 'Shrutee', 'age': 23, 'city': 'Mumbai'}


In [43]:
# Add new key
person["email"] = "revankarshruti@email.com"
print("Updated Dictionary:", person)

Updated Dictionary: {'name': 'Shrutee', 'age': 23, 'city': 'Mumbai', 'email': 'revankarshruti@email.com'}


5. SCRIPT 

In [44]:
age = 20

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


6. Print the Grade

In [45]:
marks = 90

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")

Grade: A


7.    

In [46]:
num = 0

if num > 0:
    print("Positive number")
    if num % 2 == 0:
        print("Also Even")
else:
    if num == 0:
        print("Number is Zero")
    else:
        print("Negative number")

Number is Zero


## Section B: Numpy

8. Array

In [50]:
# scalar
scalar = np.array(5)
print("Scalar:\n ", scalar)

# 1D array 
array = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", array)

# 2D array (2*3)
array2 = np.arange(10, 28, 3).reshape(2, 3)
print("2D Array:\n", array2)

Scalar:
  5
1D Array:
 [1 2 3 4 5]
2D Array:
 [[10 13 16]
 [19 22 25]]


9. 4x4 Numpy array

In [51]:
random_array = np.random.randint(0, 100, (4, 4))
print("Random 4x4 Array:\n", random_array)

Random 4x4 Array:
 [[42 67  4 27]
 [90 33 12 75]
 [68 60 70 56]
 [77 66 41 47]]


10. 2D Numpy Array 

In [53]:
array = np.random.randint(1, 50, (3, 3))
print(array)
print()
df = pd.DataFrame(array, columns = ['A', 'B', 'C'])
print(df)

[[ 3  9 41]
 [40  9 30]
 [40 40 12]]

    A   B   C
0   3   9  41
1  40   9  30
2  40  40  12


# Section C: Exploring Pandas

In [56]:
df = {
    "Name": ["Jiya", "Kishor", "Grisha", "Jay", "Maya", "Preet", "Abhay", "Bhavya", "Rakesh", "Kriya"],
    "Age": [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    "City": ["Mumbai", "Delhi", "Pune", "Chennai", "Kolkata", "Mumbai", "Delhi", "Pune", "Chennai", "Kolkata"],
    "Salary": [30000, 40000, None, 50000, 60000, 30000, 40000, None, 50000, 60000]
}

df1 = pd.DataFrame(df)
df1

,Name,Age,City,Salary
0,Jiya,21,Mumbai,30000.0
1,Kishor,22,Delhi,40000.0
2,Grisha,23,Pune,NaN
3,Jay,24,Chennai,50000.0
4,Maya,25,Kolkata,60000.0
5,Preet,26,Mumbai,30000.0
6,Abhay,27,Delhi,40000.0
7,Bhavya,28,Pune,NaN
8,Rakesh,29,Chennai,50000.0
9,Kriya,30,Kolkata,60000.0


In [57]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [58]:
df1.describe()

,Age,Salary
count,10.00000,8.000000
mean,25.50000,45000.000000
std,3.02765,11952.286093
min,21.00000,30000.000000
25%,23.25000,37500.000000
50%,25.50000,45000.000000
75%,27.75000,52500.000000
max,30.00000,60000.000000


In [59]:
print(df1[["Name", "City"]])

     Name     City
0    Jiya   Mumbai
1  Kishor    Delhi
2  Grisha     Pune
3     Jay  Chennai
4    Maya  Kolkata
5   Preet   Mumbai
6   Abhay    Delhi
7  Bhavya     Pune
8  Rakesh  Chennai
9   Kriya  Kolkata


In [60]:
df2 = df1.drop("City", axis = 1)
df2

,Name,Age,Salary
0,Jiya,21,30000.0
1,Kishor,22,40000.0
2,Grisha,23,NaN
3,Jay,24,50000.0
4,Maya,25,60000.0
5,Preet,26,30000.0
6,Abhay,27,40000.0
7,Bhavya,28,NaN
8,Rakesh,29,50000.0
9,Kriya,30,60000.0


In [61]:
df2["Salary"] = df2["Salary"].fillna(df2["Salary"].mean())
df2

,Name,Age,Salary
0,Jiya,21,30000.0
1,Kishor,22,40000.0
2,Grisha,23,45000.0
3,Jay,24,50000.0
4,Maya,25,60000.0
5,Preet,26,30000.0
6,Abhay,27,40000.0
7,Bhavya,28,45000.0
8,Rakesh,29,50000.0
9,Kriya,30,60000.0


In [65]:
df2.duplicated().sum()   # No duplicates

np.int64(0)

In [66]:
df3 = df2.drop_duplicates()
df3

,Name,Age,Salary
0,Jiya,21,30000.0
1,Kishor,22,40000.0
2,Grisha,23,45000.0
3,Jay,24,50000.0
4,Maya,25,60000.0
5,Preet,26,30000.0
6,Abhay,27,40000.0
7,Bhavya,28,45000.0
8,Rakesh,29,50000.0
9,Kriya,30,60000.0
